# vim:fileencoding=utf-8:foldmethod=marker

# BEGIN_KITTY_THEME
# Hallvard
include current-theme.conf
# END_KITTY_THEME

shell fish

enabled_layouts splits,stack,tall,*

# Splits
map ctrl+enter  launch --location=vsplit --cwd=current
map ctrl+s      layout_action rotate

# Tabs
map ctrl+t          new_tab
map ctrl+w          close_window
map ctrl+tab        next_tab
map ctrl+shift+tab  previous_tab

# Window navigation
map ctrl+h  neighboring_window left
map ctrl+l  neighboring_window right
