# --- https://wiki.hypr.land/Configuring/Monitors/ ---

monitor = DP-1, 2560x1440@59.95Hz, 0x0 ,1

# --- https://wiki.hypr.land/Configuring/Environment-variables/ ---

env = GDK_SCALE,1
env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24
env = ELECTRON_OZONE_PLATFORM_HINT,auto

env = XDG_SESSION_TYPE,             wayland
env = XDG_CURRENT_DESKTOP,          Hyprland
env = XDG_SESSION_DESKTOP,          Hyprland

# nvidia
env = LIBVA_DRIVER_NAME,            nvidia
env = GBM_BACKEND,                  nvidia-drm
env = __GLX_VENDOR_LIBRARY_NAME,    nvidia
env = __GL_GSYNC_ALLOWED,           1
env = __GL_VRR_ALLOWED,             0
env = WLR_NO_HARDWARE_CURSORS,      0

# --- https://wiki.hypr.land/Configuring/Variables/ ---

# https://wiki.hypr.land/Configuring/Variables/#input
input {
    kb_layout = no
    kb_variant = winkeys
    kb_model = logitech
    kb_options = caps:super

    follow_mouse = 1
    sensitivity = 0
    accel_profile = flat

    touchpad {
        natural_scroll = false
    }
}

# https://wiki.hypr.land/Configuring/Variables/#general
general {
    gaps_in = 4
    gaps_out = 8

    border_size = 2

    col.active_border = rgb(088199)
    col.inactive_border = rgba(08819980)

    resize_on_border = true

    allow_tearing = false

    layout = dwindle
}

# https://wiki.hypr.land/Configuring/Variables/#decoration
decoration {
    rounding = 4
    rounding_power = 2.0

    active_opacity = 0.9
    inactive_opacity = 0.4

    # https://wiki.hypr.land/Configuring/Variables/#shadow
    shadow {
        enabled = false
    }

    # https://wiki.hypr.land/Configuring/Variables/#blur
    blur {
        enabled = true
        size = 4
        passes = 1
        new_optimizations = true
    }
}

# https://wiki.hypr.land/Configuring/Animations/
animations {
    enabled = true
    animation = global, 1, 4, default
}

# https://wiki.hypr.land/Configuring/Variables/#misc
misc {
    force_default_wallpaper = 0
    disable_hyprland_logo = true
    vfr = true
}

# https://wiki.hypr.land/Configuring/Dwindle-Layout/
dwindle {
    pseudotile = true
    preserve_split = true
}

# https://wiki.hypr.land/Configuring/Master-Layout/
master {
    new_status = master
}

# --- https://wiki.hypr.land/Configuring/Window-Rules/ --- https://wiki.hypr.land/Configuring/Workspace-Rules/ ---

windowrule = suppress_event maximize, match:class .*
windowrule = no_focus on, match:class ^$, match:title ^$, match:xwayland 1, match:float 1, match:fullscreen 0, match:pin 0

windowrule = no_blur off, match:class kitty

layerrule = blur on, match:namespace wofi

layerrule = blur on, match:namespace waybar
layerrule = blur_popups on, match:namespace waybar
layerrule = ignore_alpha 0.1, match:namespace waybar
