background {
    monitor =
    color = rgb(ffffff00)

    # Set a random wallpaper.
    path =
    reload_cmd = find ~/.config/screen/wallpapers -maxdepth 1 -type f ! -name '.*' | shuf -n 1

    blur_passes = 1
    shadow_size = 0
}

input-field {
    monitor =
    fade_on_empty = false

    font_color = rgb(f2f1ef)
    font_family = JetBrainsMonoNerdFontMono
    placeholder_text =

    size = 200, 50
    halign = center
    valign = bottom
    position = 0, 30% # up from the bottom

    outline_thickness = 2
    outer_color = rgb(f2f1ef)
    inner_color = rgba(ffffff00)

    rounding = 2
    dots_rounding = 2

    dots_size = 0.25
    dots_spacing = 0.25

    # Status colors:
    fail_color = rgb(8b0000)
    fail_text =
    check_color  = rgb(088199)
    check_text =
    capslock_color =
    numlock_color =
    bothlock_color =
}

label {
    monitor =
    text = cmd[update:1000] echo "<span font_desc='300'>$(date +'%H:%M')</span><span font_desc='50'> $(date +'%S')</span>"

    color = rgb(f2f1ef)
    font_size = 300 # fallback font size
    font_family = JetBrainsMonoNerdFontMono

    halign = center
    valign = bottom
    position = 0, 45% # up from the bottom
}
label {
    monitor =
    text = cmd[update:1000] echo "<span>$(date +'%A %d. %B' | awk '{print toupper(substr($0,1,1)) substr($0,2)}')</span>"

    color = rgb(f2f1ef)
    font_size = 50
    font_family = JetBrainsMonoNerdFontMono

    halign = center
    valign = bottom
    position = 0, 40% # up from the bottom
}
