general {
    after_sleep_cmd = hyprctl dispatch dpms on
    ignore_dbus_inhibit = false
}

listener {
    timeout = 180
    on-timeout = $HOME/.config/screen/idle.sh && (pkill -STOP -f loop.sh; hyprctl dispatch dpms off)
    on-resume = hyprctl dispatch dpms on; pkill -CONT -f loop.sh
}
