exec-once = waybar
exec-once = mako
exec-once = $HOME/.config/hypr/wallpaper.sh
exec-once = swayidle -w timeout 180 '$HOME/.config/hypr/idle.sh' resume 'killall -SIGCONT wallpaper.sh && hyprctl dispatch dpms on'
