exec-once = waybar
exec-once = mako

env = PATH,$PATH:$HOME/Applications/awww/target/release
exec-once = awww-daemon
exec-once = $HOME/.config/hypr/wallpaper.sh

exec-once = swayidle -w timeout 180 '$HOME/.config/hypr/idle.sh' resume 'killall -SIGCONT wallpaper.sh && hyprctl dispatch dpms on'
